### ISSUE TITLE
todo 편집

### ISSUE THREAD

**Issue by do-coding-J** [do-coding-J/TODO#1]
- [x] 배열에 쓰레기값이 보임
- [x] 세그먼트 에러 발생4
- [x] 할일 입력시 스페이스바가 들어가는 경우 오류발생
